@ #20 | should update README file
teracyhq-incubator/kubernetes-stack-cookbook pull request #24
Opened 2017-08-16 20:06 UTC by hieptranquoc

2017-08-16 20:06 UTC, hieptranquoc commented
@hoatle review plz

2017-08-17 00:52 UTC, hoatle requested changes

2017-08-17 00:52 UTC, hoatle commented on README.md
> +  $ git clone git@github.com:<your_forked_repo>/kubernetes-stack-cookbook.git
git clone <your_forked_repo_address>

2017-08-17 00:52 UTC, hoatle commented on README.md
> +## How to use
no no, this is a standard Chef cookbook, follow README format from other Chef cookbooks, for example: https://github.com/chef-cookbooks/docker

2017-08-17 10:54 UTC, hieptranquoc commented on README.md
> +## How to use
@hoatle standard Chef cookbook ? it's a standalone chef cookbook( run without teracy-dev)
 or run with teracy-dev

2017-08-17 10:56 UTC, hoatle commented on README.md
> +## How to use
README docs don't need to mention about teracy-dev at all.

2017-08-17 19:53 UTC, hoatle requested changes
@hieptranquoc please update README with the following outline:

```
## Getting started

//TODO

## Platform support

//TODO

## Resources overview
//TODO

## How to develop
```

update README only, don't introduce new files or touch other files.

2017-08-17 19:53 UTC, hoatle commented on README.md
> +  $ git clone git@github.com:<your_forked_repo_address>/kubernetes-stack-cookbook.git
$ git checkout <your_forked_repo_address> is enough

2017-08-17 19:53 UTC, hoatle commented on dev-setup/vagrant_config_override.example.json
> +{
remove this file

2017-08-17 19:53 UTC, hoatle commented on dev-setup/vagrant_config_default.json
> +      // to work with kubernetes
don't add this

2017-08-17 19:53 UTC, hoatle commented on dev-setup/chef/run-dev.sh
> +if hash git 2>/dev/null; then
no no

2017-08-18 09:42 UTC, hieptranquoc commented on dev-setup/chef/run-dev.sh
> +if hash git 2>/dev/null; then
fixed!

2017-08-18 09:42 UTC, hieptranquoc commented on dev-setup/vagrant_config_default.json
> +      // to work with kubernetes
fixed!

2017-08-18 09:42 UTC, hieptranquoc commented on dev-setup/vagrant_config_override.example.json
> +{
fixed!

2017-08-18 09:42 UTC, hieptranquoc commented on README.md
> +  $ git clone git@github.com:<your_forked_repo_address>/kubernetes-stack-cookbook.git
fixed!

2017-08-18 09:42 UTC, hieptranquoc commented
@hoatle check this PR again,plz

2017-08-18 09:48 UTC, hoatle requested changes
review done, @hieptranquoc please see my comments.

2017-08-18 09:48 UTC, hoatle commented on README.md
> +```ruby
@hieptranquoc what's about `binary_path` option for all there resources?

2017-08-18 09:48 UTC, hoatle commented on README.md
> +## Platform Support
"Platform support", make sure everything is consistent.

2017-08-18 09:48 UTC, hoatle commented on README.md
> +- [helm](#helm): install or remove kubernetes/helm
install or remove ``helm``

2017-08-18 09:48 UTC, hoatle commented on README.md
> +- [gcloud](#gcloud): install or remove google-cloud-sdk
install or remove ``google-cloud-sdk``

2017-08-18 09:48 UTC, hoatle commented on README.md
> +- [kubectl](#kubectl): install or remove kubectl
``kubectl``

2017-08-18 09:48 UTC, hoatle commented on README.md
> +- [gcloud](#gcloud): install or remove google-cloud-sdk
highlight the programs with in ``

2017-08-18 10:11 UTC, hieptranquoc commented on README.md
> +## Platform Support
fixed!

2017-08-18 10:11 UTC, hieptranquoc commented on README.md
> +```ruby
fixed!

2017-08-18 10:11 UTC, hieptranquoc commented on README.md
> +- [gcloud](#gcloud): install or remove google-cloud-sdk
fixed!

2017-08-18 10:11 UTC, hieptranquoc commented on README.md
> +- [kubectl](#kubectl): install or remove kubectl
fixed!

2017-08-18 10:11 UTC, hieptranquoc commented on README.md
> +- [helm](#helm): install or remove kubernetes/helm
fixed!

2017-08-18 10:14 UTC, hoatle requested changes

2017-08-18 10:14 UTC, hoatle commented on README.md
> +## Resources Overview
Resources overview

2017-08-18 10:14 UTC, hoatle commented on README.md
> +## Platform Support
Platform support (the 2nd time and no changes after my 1st comment, this is bad)

2017-08-18 10:14 UTC, hoatle commented on README.md
> +## Platform Support
Using the lower, Upper case must be consistent with the same heading levels.

2017-08-18 10:16 UTC, hoatle requested changes
@hieptranquoc review done, pls check my comments.

2017-08-18 10:16 UTC, hoatle commented on README.md
> +  binary_path '' #application location (if empty,default:/usr/local/bin/kubectl)
if empty, default (1 white space after the comma character)

2017-08-18 10:16 UTC, hoatle commented on README.md
> +  binary_path '' #application location (if empty,default:/usr/local/bin/gcloud)
if empty, default (1 white space after the comma character)

2017-08-18 10:16 UTC, hoatle commented on README.md
> +  binary_path '' #application location (if empty,default:/usr/local/bin/helm)
if empty, default (1 white space after the comma character)

2017-08-18 10:18 UTC, hieptranquoc commented on README.md
> +  binary_path '' #application location (if empty,default:/usr/local/bin/helm)
@hoatle fixed!

2017-08-18 10:18 UTC, hieptranquoc commented on README.md
> +  binary_path '' #application location (if empty,default:/usr/local/bin/gcloud)
fixed!

2017-08-18 10:18 UTC, hieptranquoc commented on README.md
> +  binary_path '' #application location (if empty,default:/usr/local/bin/kubectl)
fixed!

2017-08-18 10:18 UTC, hieptranquoc commented on README.md
> +## Resources Overview
fixed!

2017-08-18 10:18 UTC, hieptranquoc commented on README.md
> +## Platform Support
fixed!

2017-08-18 10:35 UTC, hieptranquoc commented
@hoatle fixed!

2017-08-18 10:40 UTC, hoatle approved these changes
LGTM

2017-08-18 10:40 UTC, merged